CREATE TABLE `section` (
	`id` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `section_unique` (`name`) USING BTREE
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;